name: Build APK
on: [push]
jobs:
  build:
    # استخدام الإصدار الأحدث والأسرع
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # تثبيت المكتبات الناقصة يدوياً لتجنب خطأ libtinfo5
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo5 libncurses5

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
