name: Build APK
on: [push]
jobs:
  build:
    # استخدام إصدار 20.04 يضمن توفر المكتبات القديمة المطلوبة
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
